feed/feed/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include('post.urls')),
    url(r'^admin/', admin.site.urls),
]

feed/post/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = "post"

urlpatterns = [
	# url(r'^blog/$', views.BlogView.as_view(), name='blog'),
	url(r'^feed/$', views.FeedView.as_view(), name='feed'),
	url(r'^users/$', views.UsersView.as_view(), name='users'),
	url(r'^logout/$', LogoutView.as_view(), name='logout'),
	url(r'^login/$', LoginView.as_view(template_name='post/login.html'), name='login'),
	# url(r'^login/$', views.LoginView.as_view(), name='login'),
	url(r'^dashboard/$', views.Dashboard.as_view(), name='dashboard'),
	url(r'^post/add/$', views.PostCreate.as_view(), name='post_add'),
	url(r'^post/(?P<pk>[\d]+)/$', views.PostDetail.as_view(), name='post_detail'),
    url(r'^$', views.Home.as_view(), name='home'),
]

feed/post/models.py
from django.db import models
from django.urls import reverse, reverse_lazy
from django.utils.timezone import now
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField(max_length=1000)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(default=now)
    read = models.BooleanField(default=False)

    def __str__(self):
        return f'title:{self.title}, author: {self.author}, time: {self.creation_date}'

    def get_absolute_url(self):
        return reverse_lazy('post_detail', args=[self.pk])


class Follower(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name='owner', null=True, on_delete=models.CASCADE)

    @classmethod
    def follow(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.add(new_friend)

    @classmethod
    def unfollow(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.remove(new_friend)

feed/post/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, TemplateView, FormView, UpdateView
from django.views import View
# Create your views here.
from .models import Post, Follower
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.views import LoginView, LogoutView

from django.contrib.auth.models import User


class Home(ListView):
    # Хочу відфільтрувати пости, щоб відображались лише пости юзерів яких фоловить залогінений юзер
    # queryset = Post.objects.exclude(author__users=request.user)
    model = Post
    template_name = 'post/home.html'
    context_object_name = 'posts'
    ordering = '-creation_date'
    paginate_by = 3


class UsersView(TemplateView):
    template_name = 'post/users.html'

    def get(self, request):
        users = User.objects.exclude(id=request.user.id)
        follows = Follower.objects.get(current_user=request.user)
        follows = follows.users.all()

        args = {
            'users': users, 'follows': follows
        }
        return render(request, self.template_name, args)


@method_decorator(login_required, name='dispatch')
class Dashboard(View):
    login_url = 'post/login.html'

    def get(self, request, *args, **kwargs):
        view = Home.as_view(
            template_name = 'post/admin_page.html',
            paginate_by = 4
        )
        return view(request, *args, **kwargs)


class PostDetail(DetailView):
    model = Post

    def get_object(self):
        object = super(PostDetail, self).get_object()
        # object.read = True
        # object.save()
        return object


class PostCreate(CreateView):
    model = Post
    fields = ('title', 'body')

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.save()
        return super(PostCreate, self).form_valid(form)


# @login_required(login_url='/accounts/login/')
class FeedView(UpdateView):
    template_name = 'post/feed.html'

    def get(self, request, *args, **kwargs):
        follows = Follower.objects.get(current_user=request.user)
        follows = follows.users.all()
        posts = Post.objects.all().filter(author__in=follows).order_by('-creation_date')
        args = {
            'posts': posts, 'follows': follows
        }
        return render(request, self.template_name, args)


class MarkAsReadView(UpdateView):
    model = Post
    fields = ['read']
    template_name = 'post/feed.html'

feed/post/templates/post/admin_page.html
{% extends 'post/base.html' %}

{% block breadcrumb %}{{ block.super }} > Admin{% endblock %}

{% block content %}

    <div class="blog-table">
        <h2><a href="#">&#9997 New Post</a> </h2>
        <table>
            <tr>
                <th>Title</th>
                <th colspan="2">Actions</th>
            </tr>
            {% for post in posts %}
                <tr>
                    <td>{{ post.title }}</td>
                    <td><a href="#">&#9998 Edit</a> </td>
                    <td><a href="#">&#128465 Delete</a> </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    {% include 'post/pagination_links.html' %}
{% endblock %}

feed/post/templates/post/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Blog{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'post/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'post/css/style.css' %}">
</head>
<body>

    <nav>
        <h2>&#x1f440 News blog</h2>
        {% if user.is_authenticated %}
            <p class="nav"><a href="{% url 'post:users' %}">Users</a></p>
            <p class="nav"><a href="{% url 'post:post_add' %}">Add post</a> </p>
            <p><a href="#">&#128274 Logout</a></p>
        {% else %}
            <p><a href="{% url 'post:login' %}">&#128275 Login</a></p>
        {% endif %}
    </nav>

    <section class="content-wrapper">
        <div class="breadcrumb">
            <p>{% block breadcrumb %}<a href="{% url 'post:home' %}">Home</a>{% endblock %}</p>
        </div>

        {% block content %}

        {% endblock %}
    </section>

</body>
</html>

feed/post/templates/post/feed.html
{% extends 'post/base.html' %}

{% load static %}

{% block breadcrumb %}{{ block.super }} > Feed {% endblock %}

{% block content %}
    {% for post in posts %}
    <div class="blog-item">
        <h1>{{ post.author }}</h1>
            <h2>{{ post.title }} </h2>
            <div class="info">
                Created On <span>{{ post.creation_date }}</span>
            </div>
            <p> {{ post.body  }}</p>
            {% if post.read == False %}
                <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p><input type="submit" value="Mark as seen"></p>
                </form>
            {% else %}
                <button type="button" class="btn btn-success">Mark as unseen</button>
            {% endif %}
        </div>
    {% endfor %}
    {% include 'post/pagination_links.html' %}

{% endblock %}

feed/post/templates/post/home.html
{% extends 'post/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="blog-item">
            <h2><a href="{% url 'post:post_detail' post.pk %}">{{ post.title }} </a> </h2>
            <div class="info">
                By <span><a href="#">{{ post.author }}</a></span> | On <span>{{ post.creation_date }}</span>
            </div>
            <p> {{ post.body | truncatewords:30 }}</p>
                {% if post.read == True %}
                    <h6>seen</h6>
                {% else %}
                    <h6>Unseen. open to read</h6>
                {% endif %}
        </div>
    {% empty %}
        <div>
            <h3>There are no posts yet.</h3>
        </div>
    {% endfor %}
    {% include 'post/pagination_links.html' %}
{% endblock %}

feed/post/templates/post/login.html
{% extends 'post/base.html' %}

{% block breadcrumb %}{% endblock %}

{% block content %}

    <div class="form login-form">
        <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <p><input type="submit" value="Login"></p>
        </form>
    </div>

{% endblock %}

feed/post/templates/post/pagination_links.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

feed/post/templates/post/post_detail.html
{% extends 'post/base.html' %}

{% load static %}

{% block breadcrumb %}{{ block.super }} > {{ post.title }} {% endblock %}

{% block content %}

    <div class="blog-item">
            <h2>{{ post.title }} </h2>
            <div class="info">
                By <span><a href="#">{{ post.author }}</a></span> | On <span>{{ post.creation_date }}</span>
            </div>
            <p> {{ post.body  }}</p>
        </div>

    <div class="form">
        <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
        </form>
    </div>


{% endblock %}

feed/post/templates/post/post_form.html
{% extends 'post/base.html' %}

{% block breadcrumb %}{{ block.super }} > Admin page > New Post{% endblock %}

{% block content %}

    <div class="form">
        <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <p><input type="submit" value="Submit"></p>
        </form>
    </div>

{% endblock %}

feed/post/templates/post/users.html
{% extends 'post/base.html' %}

{% block content %}
    <div class="col-lg-4">
        <h2>People</h2>
        <div class="blog-item">
        {% for user in users %}
            {{ user.username }}
            {% if not user in friends %}
                <a href="#">
                <button type="button" class="btn btn-success">Follow</button>
                </a>
            {% endif %}
        {% endfor %}

        <h2>Following</h2>
        {% for follow in follows %}
            <a href="#">
                {{ follow.username }}
            </a>
            <a href="#">
            <button type="button" class="btn btn-default">Unfollow</button>
            </a>
        {% endfor %}
            </div>
    </div>
{% endblock %}